# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 541))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 100, 801, 441))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.picview_source = QtWidgets.QGraphicsView(self.horizontalLayoutWidget)
        self.picview_source.setObjectName("picview_source")
        self.horizontalLayout_3.addWidget(self.picview_source)
        self.picview_result = QtWidgets.QGraphicsView(self.horizontalLayoutWidget)
        self.picview_result.setObjectName("picview_result")
        self.horizontalLayout_3.addWidget(self.picview_result)
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionss = QtWidgets.QAction(MainWindow)
        self.actionss.setObjectName("actionss")
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setCheckable(False)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionStorage_File = QtWidgets.QAction(MainWindow)
        self.actionStorage_File.setObjectName("actionStorage_File")
        self.action_sobel = QtWidgets.QAction(MainWindow)
        self.action_sobel.setObjectName("action_sobel")
        self.action_prewitt = QtWidgets.QAction(MainWindow)
        self.action_prewitt.setObjectName("action_prewitt")
        self.action_laplace = QtWidgets.QAction(MainWindow)
        self.action_laplace.setObjectName("action_laplace")
        self.action_genrate = QtWidgets.QAction(MainWindow)
        self.action_genrate.setObjectName("action_genrate")
        self.action_LOG = QtWidgets.QAction(MainWindow)
        self.action_LOG.setObjectName("action_LOG")
        self.action_maximus = QtWidgets.QAction(MainWindow)
        self.action_maximus.setObjectName("action_maximus")
        self.menu.addAction(self.actionOpen_File)
        self.menu.addAction(self.actionStorage_File)
        self.menu_2.addAction(self.action_sobel)
        self.menu_2.addAction(self.action_prewitt)
        self.menu_2.addAction(self.action_laplace)
        self.menu_3.addAction(self.action_genrate)
        self.menu_3.addAction(self.action_LOG)
        self.menu_3.addAction(self.action_maximus)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.actionOpen_File.triggered.connect(self.picview_source.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "数字图像"))
        self.label.setText(_translate("MainWindow", "原始图像"))
        self.label_2.setText(_translate("MainWindow", "处理图像"))
        self.menu.setTitle(_translate("MainWindow", "文件(&F)"))
        self.menu_2.setTitle(_translate("MainWindow", "边缘检测"))
        self.menu_3.setTitle(_translate("MainWindow", "阈值分割"))
        self.actionss.setText(_translate("MainWindow", "ss"))
        self.actionOpen_File.setText(_translate("MainWindow", "打开文件(&O)"))
        self.actionOpen_File.setToolTip(_translate("MainWindow", "Ctrl+O"))
        self.actionStorage_File.setText(_translate("MainWindow", "储存文件(&S)"))
        self.actionStorage_File.setToolTip(_translate("MainWindow", "Ctrl+S"))
        self.action_sobel.setText(_translate("MainWindow", "sobel"))
        self.action_prewitt.setText(_translate("MainWindow", "prewitt"))
        self.action_laplace.setText(_translate("MainWindow", "拉普拉斯"))
        self.action_genrate.setText(_translate("MainWindow", "迭代阈值"))
        self.action_LOG.setText(_translate("MainWindow", "LOG"))
        self.action_maximus.setText(_translate("MainWindow", "一维最大熵"))
